version: "3.7"
services:
  web:
    build: project
    restart: always
    ports:
      - "8000:8000"

    networks:
      - flask_network


  proxy:
    build: proxy
    restart: always
    ports:
      - "80:80"
    networks:
      - flask_network

  db:
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    networks:
      - flask_network
    environment:
      - POSTGRES_USER=evgenijzupanik
      - POSTGRES_PASSWORD=123456
      - POSTGRES_DB=flask_db4
    volumes:
      - postgres_data:/var/lib/postgresql/data

networks:
  flask_network:
volumes:
  postgres_data: